"""SQLAlchemy 2.0 table definitions for CAL-ACCESS tables.

Auto-generated from migrations/0001_create_all_tables.sql — keep in sync.
Used by the ETL loader for type-aware validation and upsert logic.

These definitions mirror the Postgres DDL exactly. For partitioned tables
(rcpt_cd, exppd_cd, loans_cd), the parent table is defined here; individual
partition child tables are created during ETL ingestion as new year data arrives.
"""

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
)

metadata = MetaData()
# Naming convention for constraints: {table_name}_{column_names}_{type}
metadata.naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# =============================================================================
# 1. Reference / Dimension Tables
# =============================================================================

lookup_codes = Table(
    "lookup_codes", metadata,
    Column("code_type", String(50), primary_key=True, nullable=False),
    Column("code_id", String(50), primary_key=True, nullable=False),
    Column("code_desc", Text),
)

acronyms = Table(
    "acronyms", metadata,
    Column("acronym", String(20), primary_key=True, nullable=False),
    Column("stands_for", Text, nullable=False),
    Column("effect_dt", Date),
    Column("a_desc", Text),
)

filer_types = Table(
    "filer_types", metadata,
    Column("filer_type", String(20), primary_key=True, nullable=False),
    Column("description", Text),
    Column("grp_type", String(20)),
    Column("calc_use", String(10)),
    Column("grace_period", Integer),
)

filer_status_types = Table(
    "filer_status_types", metadata,
    Column("status_type", String(20), primary_key=True, nullable=False),
    Column("status_desc", Text),
)

group_types = Table(
    "group_types", metadata,
    Column("grp_id", String(20), primary_key=True, nullable=False),
    Column("grp_name", String(100)),
    Column("grp_desc", Text),
)

report_types = Table(
    "report_types", metadata,
    Column("rpt_id", String(20), primary_key=True, nullable=False),
    Column("rpt_name", String(100)),
    Column("rpt_desc", Text),
    Column("path", Text),
    Column("data_object", Text),
    Column("parms_flg_y_n", Boolean),
    Column("rpt_type", String(20)),
    Column("parm_definition", Text),
)

legislative_sessions = Table(
    "legislative_sessions", metadata,
    Column("session_id", Integer, primary_key=True, nullable=False),
    Column("begin_date", Date, nullable=False),
    Column("end_date", Date, nullable=False),
)

filing_periods = Table(
    "filing_periods", metadata,
    Column("period_id", String(30), primary_key=True, nullable=False),
    Column("start_date", Date, nullable=False),
    Column("end_date", Date, nullable=False),
    Column("period_type", String(20)),
    Column("per_grp_type", String(20)),
    Column("period_desc", Text),
    Column("deadline", Date),
)

filing_types = Table(
    "filing_types", metadata,
    Column("filing_type", String(30), primary_key=True, nullable=False),
)

# =============================================================================
# 2. Entity / Committee Tables
# =============================================================================

filers = Table(
    "filers", metadata,
    Column("filer_id", String(20), primary_key=True, nullable=False),
    Column("source", String(20), default="calaccess"),
)

filername = Table(
    "filername", metadata,
    Column("xref_filer_id", String(20)),
    Column("filer_id", String(20), nullable=False),
    Column("filer_type", String(20)),
    Column("status", String(20)),
    Column("effect_dt", Date),
    Column("naml", String(120)),
    Column("namf", String(30)),
    Column("namt", String(40)),
    Column("nams", String(30)),
    Column("adr1", String(80)),
    Column("adr2", String(80)),
    Column("city", String(40)),
    Column("st", String(2)),
    Column("zip4", String(10)),
    Column("phon", String(20)),
    Column("fax", String(20)),
    Column("email", String(100)),
    Column("cand_office", String(60)),
    Column("cand_dist", Integer),
    Column("cand_yr", Integer),
    Column("cand_county", String(30)),
    Column("cand_election_type", String(30)),
    Column("cand_party", String(10)),
)

address_master = Table(
    "address_master", metadata,
    Column("adrid", String(30), primary_key=True, nullable=False),
    Column("city", String(40)),
    Column("st", String(2)),
    Column("zip4", String(10)),
    Column("phon", String(20)),
    Column("fax", String(20)),
    Column("email", String(100)),
)

filer_address = Table(
    "filer_address", metadata,
    Column("filer_id", String(20)),
    Column("adrid", String(30)),
    Column("effect_dt", Date),
    Column("add_type", String(20)),
    Column("session_id", Integer),
)

filer_xref = Table(
    "filer_xref", metadata,
    Column("filer_id", String(20)),
    Column("xref_id", String(20), nullable=False),
    Column("effect_dt", Date),
    Column("migration_source", String(50)),
)

filer_links = Table(
    "filer_links", metadata,
    Column("filer_id_a", String(20)),
    Column("filer_id_b", String(20), nullable=False),
    Column("active_flg", Boolean, default=True),
    Column("session_id", Integer),
    Column("link_type", String(20)),
    Column("link_desc", Text),
    Column("effect_dt", Date),
    Column("dominate_filer", String(20)),
    Column("termination_dt", Date),
)

filer_type_assignments = Table(
    "filer_type_assignments", metadata,
    Column("filer_id", String(20)),
    Column("filer_type", String(20)),
    Column("active", Boolean, default=True),
    Column("race", Boolean),
    Column("session_id", Integer),
    Column("category", String(50)),
    Column("category_type", String(50)),
    Column("sub_category", String(50)),
    Column("effect_dt", Date),
    Column("sub_category_type", String(50)),
    Column("election_type", String(30)),
    Column("sub_category_a", String(30)),
    Column("nyq_dt", Date),
    Column("party_cd", String(10)),
    Column("county_cd", String(10)),
)

filer_ethics_class = Table(
    "filer_ethics_class", metadata,
    Column("filer_id", String(20)),
    Column("session_id", Integer),
    Column("ethics_date", Date),
)

filer_interests = Table(
    "filer_interests", metadata,
    Column("filer_id", String(20)),
    Column("session_id", Integer),
    Column("interest_cd", String(20)),
    Column("effect_date", Date),
)

filer_acronyms = Table(
    "filer_acronyms", metadata,
    Column("acronym", String(20)),
    Column("filer_id", String(20)),
)

names_master = Table(
    "names_master", metadata,
    Column("namid", String(30), primary_key=True, nullable=False),
    Column("naml", String(120)),
    Column("namf", String(30)),
    Column("namt", String(40)),
    Column("nams", String(30)),
    Column("moniker", String(30)),
    Column("moniker_pos", Integer),
    Column("namm", String(30)),
    Column("fullname", String(300)),
    Column("naml_search", String(200)),
    Column("created_at", DateTime),
    Column("updated_at", DateTime),
)

# =============================================================================
# 3. Filing / Report Tables
# =============================================================================

filings = Table(
    "filings", metadata,
    Column("filing_id", String(30), primary_key=True, nullable=False),
    Column("filing_type", String(30)),
    Column("filer_id", String(20)),
    Column("form_id", String(30)),
    Column("filing_date", Date),
    Column("amend_id", String(30)),
    Column("period_id", String(30)),
    Column("election_date", Date),
    Column("election_type", String(30)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
    Column("stmnt_type", String(20)),
    Column("stmnt_status", String(20)),
    Column("session_id", Integer),
    Column("user_id", String(30)),
    Column("special_audit", Boolean, default=False),
    Column("fine_audit", Boolean, default=False),
    Column("rpt_start", Date),
    Column("rpt_end", Date),
    Column("rpt_date", Date),
)

efs_filing_log = Table(
    "efs_filing_log", metadata,
    Column("filing_date", Date),
    Column("filing_status", String(20)),
    Column("vendor", String(50)),
    Column("filer_id", String(20)),
    Column("form_type", String(30)),
    Column("error_no", Integer),
)

received_filings = Table(
    "received_filings", metadata,
    Column("filer_id", String(20)),
    Column("filing_file_name", String(200)),
    Column("received_date", Date),
    Column("filing_directory", String(200)),
    Column("filing_id", String(30)),
    Column("form_id", String(30)),
    Column("receive_comment", Text),
)

hdr = Table(
    "hdr", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("ef_type", String(10)),
    Column("state_cd", String(10)),
    Column("cal_ver", String(10)),
    Column("soft_name", String(50)),
    Column("soft_ver", String(20)),
    Column("hdrcomment", Text),
)

header_defs = Table(
    "header_defs", metadata,
    Column("line_number", Integer),
    Column("form_id", String(30)),
    Column("rec_type", String(10)),
    Column("section_label", String(100)),
    Column("comments1", Text),
    Column("comments2", Text),
    Column("label", String(100)),
    Column("column_a", String(50)),
    Column("column_b", String(50)),
    Column("column_c", String(50)),
    Column("show_c", String(10)),
    Column("show_b", String(10)),
)

image_links = Table(
    "image_links", metadata,
    Column("img_link_id", String(30), primary_key=True, nullable=False),
    Column("img_link_type", String(20)),
    Column("img_id", String(30)),
    Column("img_type", String(10)),
    Column("img_dt", Date),
)

# =============================================================================
# 4. Core Fact Tables
# =============================================================================

rcpt_cd = Table(
    "rcpt_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("ctrib_naml", String(120)),
    Column("ctrib_namf", String(30)),
    Column("ctrib_namt", String(40)),
    Column("ctrib_nams", String(30)),
    Column("ctrib_city", String(40)),
    Column("ctrib_st", String(2)),
    Column("ctrib_zip4", String(10)),
    Column("ctrib_emp", String(120)),
    Column("ctrib_occ", String(70)),
    Column("amount", Numeric(15, 2)),
    Column("payd_by", String(10)),
    Column("payment_description", Text),
    Column("receipt_dt", Date),
    Column("disc_dtype", String(10)),
    Column("indemp", String(10)),
    Column("indocc", String(70)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("disp_first", String(30)),
    Column("disp_last", String(120)),
    Column("d_c_d_a", Date),
    Column("d_c_d_b", Date),
    Column("d_c_d_c", Date),
    Column("d_c_d_d", Date),
    Column("filer_id", String(20)),
    Column("cand_naml", String(120)),
    Column("cand_namf", String(30)),
    Column("cand_namt", String(40)),
    Column("cand_nams", String(30)),
    Column("cand_city", String(40)),
    Column("cand_st", String(2)),
    Column("cand_zip4", String(10)),
    Column("committee_id", String(20)),
    Column("comm_naml", String(120)),
    Column("comm_namf", String(30)),
    Column("comm_namt", String(40)),
    Column("comm_nams", String(30)),
    Column("mail_addr", String(80)),
    Column("mail_city", String(40)),
    Column("mail_st", String(2)),
    Column("mail_zip4", String(10)),
    Column("phone", String(20)),
    Column("consp_code", String(10)),
    Column("office_sought", String(60)),
    Column("office_dist", Integer),
    Column("election_type", String(30)),
    Column("election_date", Date),
    Column("ballot_issue", Text),
    Column("jurisdiction", String(60)),
    Column("ballot_sub_jurisdiction", String(60)),
)

cntrb_cd = Table(
    "cntrb_cd", metadata,
    Column("ctrib_id", String(30), primary_key=True, nullable=False),
    Column("ctrib_naml", String(120)),
    Column("ctrib_namf", String(30)),
    Column("ctrib_namt", String(40)),
    Column("ctrib_nams", String(30)),
    Column("ctrib_city", String(40)),
    Column("ctrib_st", String(2)),
    Column("ctrib_zip4", String(10)),
    Column("ctrib_emp", String(120)),
    Column("ctrib_occ", String(70)),
    Column("total_gives", Numeric(15, 2)),
    Column("total_year", Numeric(15, 2)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
    Column("created_at", DateTime),
    Column("updated_at", DateTime),
)

exppd_cd = Table(
    "exppd_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("payee_naml", String(120)),
    Column("payee_namf", String(30)),
    Column("payee_namt", String(40)),
    Column("payee_nams", String(30)),
    Column("payee_city", String(40)),
    Column("payee_st", String(2)),
    Column("payee_zip4", String(10)),
    Column("expn_date", Date),
    Column("expn_dscr", Text),
    Column("amount", Numeric(15, 2)),
    Column("loan_id", String(30)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("payor_naml", String(120)),
    Column("payor_namf", String(30)),
    Column("payor_namt", String(40)),
    Column("payor_nams", String(30)),
    Column("payor_city", String(40)),
    Column("payor_st", String(2)),
    Column("payor_zip4", String(10)),
    Column("refund_to_naml", String(120)),
    Column("refund_to_namf", String(30)),
    Column("refund_to_namt", String(40)),
    Column("refund_to_nams", String(30)),
    Column("refund_to_city", String(40)),
    Column("refund_to_st", String(2)),
    Column("refund_to_zip4", String(10)),
    Column("filer_id", String(20)),
)

loans_cd = Table(
    "loans_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("loan_type", String(10)),
    Column("entity_cd", String(10)),
    Column("lnr_naml", String(120)),
    Column("lnr_namf", String(30)),
    Column("lnr_namt", String(40)),
    Column("lnr_nams", String(30)),
    Column("loan_city", String(40)),
    Column("loan_st", String(2)),
    Column("loan_zip4", String(10)),
    Column("loan_amt", Numeric(15, 2)),
    Column("loan_dt", Date),
    Column("interest_rt", Numeric(7, 4)),
    Column("interest_yn", Boolean),
    Column("repmt_amt", Numeric(15, 2)),
    Column("repmt_dt", Date),
    Column("loan_purpose", Text),
    Column("balance_due", Numeric(15, 2)),
    Column("repmt_schedule", Text),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
    Column("cmte_id", String(20)),
    Column("payor_naml", String(120)),
    Column("payor_namf", String(30)),
    Column("payor_namt", String(40)),
    Column("payor_nams", String(30)),
    Column("payor_city", String(40)),
    Column("payor_st", String(2)),
    Column("payor_zip4", String(10)),
)

inttrf_cd = Table(
    "inttrf_cd", metadata,
    Column("tran_id", String(30), primary_key=True, nullable=False),
    Column("filing_id", String(30), nullable=False),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("entitty_cd", String(10)),
    Column("tran_dt", Date),
    Column("amount", Numeric(15, 2)),
    Column("tran_type", String(10)),
    Column("cmte_id", String(20)),
    Column("cmte_name", String(120)),
    Column("cmte_addr", String(80)),
    Column("cmte_city", String(40)),
    Column("cmte_st", String(2)),
    Column("cmte_zip4", String(10)),
    Column("ref_dt", Date),
    Column("ref_amt", Numeric(15, 2)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

debt_cd = Table(
    "debt_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("payee_naml", String(120)),
    Column("payee_namf", String(30)),
    Column("payee_namt", String(40)),
    Column("payee_nams", String(30)),
    Column("payee_city", String(40)),
    Column("payee_st", String(2)),
    Column("payee_zip4", String(10)),
    Column("beg_bal", Numeric(15, 2)),
    Column("debts_inc", Numeric(15, 2)),
    Column("debts_paid", Numeric(15, 2)),
    Column("end_bal", Numeric(15, 2)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

# =============================================================================
# 5. Supporting Fact Tables
# =============================================================================

smry_cd = Table(
    "smry_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("amount_a", Numeric(15, 2)),
    Column("amount_b", Numeric(15, 2)),
    Column("amount_c", Numeric(15, 2)),
    Column("elec_dt", Date),
)

splts_cd = Table(
    "splts_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("pform_type", String(10)),
    Column("ptran_id", String(30)),
    Column("elec_date", Date),
    Column("elec_amount", Numeric(15, 2)),
    Column("elec_code", String(10)),
)

text_memo = Table(
    "text_memo", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("ref_no", String(30)),
    Column("text4000", Text),
)

# =============================================================================
# 6. Disclosure Reports (CVR)
# =============================================================================

cvr_campaign_disclosure = Table(
    "cvr_campaign_disclosure", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("filer_id", String(20)),
    Column("entity_cd", String(10)),
    Column("filer_naml", String(120)),
    Column("filer_namf", String(30)),
    Column("filer_namt", String(40)),
    Column("filer_nams", String(30)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("stmt_type", String(20)),
    Column("late_rptno", Integer),
    Column("from_date", Date),
    Column("thru_date", Date),
    Column("elect_date", Date),
    Column("cash_on_hand", Numeric(15, 2)),
    Column("total_contributions", Numeric(15, 2)),
    Column("total_expenditures", Numeric(15, 2)),
    Column("loans_received", Numeric(15, 2)),
    Column("loan_repayments", Numeric(15, 2)),
    Column("other_loans", Numeric(15, 2)),
    Column("other_payments", Numeric(15, 2)),
    Column("debts_owed", Numeric(15, 2)),
    Column("net_change", Numeric(15, 2)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
    Column("signatory_name", String(120)),
    Column("signatory_title", String(60)),
    Column("prepared_by", String(120)),
    Column("prepared_phone", String(20)),
)

cvr_registration = Table(
    "cvr_registration", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("sender_id", String(20)),
    Column("filer_id", String(20)),
    Column("entity_cd", String(10)),
    Column("filer_naml", String(120)),
    Column("filer_namf", String(30)),
    Column("filer_namt", String(40)),
    Column("filer_nams", String(30)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("ls_beg_yr", Integer),
    Column("ls_end_yr", Integer),
    Column("committee_type", String(20)),
    Column("cand_id", String(20)),
    Column("cand_name", String(120)),
    Column("cand_office", String(60)),
    Column("cand_dist", Integer),
    Column("cand_county", String(30)),
    Column("cand_party", String(10)),
    Column("cand_election_type", String(30)),
    Column("cand_yr", Integer),
    Column("party", String(10)),
    Column("auth_name", String(120)),
    Column("auth_phone", String(20)),
    Column("auth_address", String(80)),
    Column("auth_city", String(40)),
    Column("auth_st", String(2)),
    Column("auth_zip4", String(10)),
    Column("mail_addr", String(80)),
    Column("mail_city", String(40)),
    Column("mail_st", String(2)),
    Column("mail_zip4", String(10)),
    Column("incrb_dt", Date),
    Column("incrb_state", String(20)),
    Column("treas_name", String(120)),
    Column("treas_phone", String(20)),
    Column("treas_address", String(80)),
    Column("treas_city", String(40)),
    Column("treas_st", String(2)),
    Column("treas_zip4", String(10)),
    Column("filing_sequence", Integer),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
    Column("signatory_name", String(120)),
    Column("signatory_title", String(60)),
)

cvr_so = Table(
    "cvr_so", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("filer_id", String(20)),
    Column("entity_cd", String(10)),
    Column("filer_naml", String(120)),
    Column("filer_namf", String(30)),
    Column("filer_namt", String(40)),
    Column("filer_nams", String(30)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("qual_cb", Boolean),
    Column("qualfy_dt", Date),
    Column("term_date", Date),
    Column("term_code", String(20)),
    Column("filing_sequence", Integer),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

cvr_lobby_disclosure = Table(
    "cvr_lobby_disclosure", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("sender_id", String(20)),
    Column("filer_id", String(20)),
    Column("entity_cd", String(10)),
    Column("filer_naml", String(120)),
    Column("filer_namf", String(30)),
    Column("filer_namt", String(40)),
    Column("filer_nams", String(30)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("from_date", Date),
    Column("thru_date", Date),
    Column("lby_orgn_naml", String(120)),
    Column("lby_orgn_namf", String(30)),
    Column("lby_orgn_namt", String(40)),
    Column("lby_orgn_nams", String(30)),
    Column("lby_orgn_adr", String(80)),
    Column("lby_orgn_city", String(40)),
    Column("lby_orgn_st", String(2)),
    Column("lby_orgn_zip4", String(10)),
    Column("lby_orgn_phon", String(20)),
    Column("lby_orgn_fax", String(20)),
    Column("lby_orgn_email", String(100)),
    Column("principal_id", String(20)),
    Column("principal_name", String(120)),
    Column("principal_adr", String(80)),
    Column("principal_city", String(40)),
    Column("principal_st", String(2)),
    Column("principal_zip4", String(10)),
    Column("lby_reg_id", String(30)),
    Column("lby_reg_name", String(120)),
    Column("filing_sequence", Integer),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

cvr2_campaign_disclosure = Table(
    "cvr2_campaign_disclosure", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("title", String(60)),
    Column("mail_city", String(40)),
    Column("mail_st", String(2)),
    Column("mail_zip4", String(10)),
    Column("f460_part", String(10)),
    Column("cmte_id", String(20)),
    Column("enty_naml", String(120)),
    Column("enty_namf", String(30)),
    Column("enty_naml_search", String(200)),
    Column("enty_namf_search", String(200)),
    Column("enty_city", String(40)),
    Column("enty_st", String(2)),
    Column("enty_zip4", String(10)),
    Column("enty_phone", String(20)),
    Column("enty_fax", String(20)),
    Column("enty_email", String(100)),
    Column("item_amt", Numeric(15, 2)),
    Column("item_dt", Date),
    Column("item_desc", Text),
)

cvr2_lobby_disclosure = Table(
    "cvr2_lobby_disclosure", metadata,
    Column("amend_id", String(30)),
    Column("entity_cd", String(10)),
    Column("entity_id", String(30)),
    Column("enty_namf", String(30)),
    Column("enty_naml", String(120)),
    Column("enty_nams", String(30)),
    Column("enty_namt", String(40)),
    Column("enty_title", String(60)),
    Column("filing_id", String(30)),
    Column("form_type", String(10)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("tran_id", String(30)),
)

cvr3_verification_info = Table(
    "cvr3_verification_info", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("sig_date", Date),
    Column("sig_loc", String(80)),
    Column("sig_naml", String(120)),
    Column("sig_namf", String(30)),
    Column("sig_namt", String(40)),
    Column("sig_nams", String(30)),
)

cvr_e530 = Table(
    "cvr_e530", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("entity_cd", String(10)),
    Column("filer_naml", String(120)),
    Column("filer_namf", String(30)),
    Column("filer_namt", String(40)),
    Column("filer_nams", String(30)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("filer_city", String(40)),
    Column("filer_st", String(2)),
    Column("filer_zip4", String(10)),
    Column("occupation", String(70)),
    Column("employer", String(120)),
    Column("cand_id", String(20)),
    Column("cand_naml", String(120)),
    Column("cand_namf", String(30)),
    Column("cand_namt", String(40)),
    Column("cand_nams", String(30)),
    Column("cand_office", String(60)),
    Column("cand_dist", Integer),
    Column("cand_county", String(30)),
    Column("cand_party", String(10)),
    Column("cand_election_type", String(30)),
    Column("cand_yr", Integer),
    Column("cash_on_hand", Numeric(15, 2)),
    Column("contributions", Numeric(15, 2)),
    Column("expenditures", Numeric(15, 2)),
    Column("debts_owed", Numeric(15, 2)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

cvr_f470 = Table(
    "cvr_f470", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("filer_id", String(20)),
    Column("entity_cd", String(10)),
    Column("filer_naml", String(120)),
    Column("filer_namf", String(30)),
    Column("filer_namt", String(40)),
    Column("filer_nams", String(30)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("cand_city", String(40)),
    Column("cand_st", String(2)),
    Column("cand_zip4", String(10)),
    Column("occupation", String(70)),
    Column("employer", String(120)),
    Column("cand_office", String(60)),
    Column("cand_dist", Integer),
    Column("cand_county", String(30)),
    Column("cand_party", String(10)),
    Column("cand_election_type", String(30)),
    Column("cand_yr", Integer),
)

# =============================================================================
# 7. Schedule Tables (Form-Specific)
# =============================================================================

s401_cd = Table(
    "s401_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("agent_naml", String(120)),
    Column("agent_namf", String(30)),
    Column("agent_namt", String(40)),
    Column("agent_nams", String(30)),
    Column("payee_naml", String(120)),
    Column("payee_namf", String(30)),
    Column("payee_namt", String(40)),
    Column("payee_nams", String(30)),
    Column("payee_city", String(40)),
    Column("payee_st", String(2)),
    Column("payee_zip4", String(10)),
    Column("expn_date", Date),
    Column("expn_amt", Numeric(15, 2)),
    Column("expn_dscr", Text),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
    Column("cmte_id", String(20)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

s496_cd = Table(
    "s496_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("amount", Numeric(15, 2)),
    Column("exp_date", Date),
    Column("expn_dscr", Text),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("date_thru", Date),
)

s497_cd = Table(
    "s497_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("enty_naml", String(120)),
    Column("enty_namf", String(30)),
    Column("enty_namt", String(40)),
    Column("enty_nams", String(30)),
    Column("enty_city", String(40)),
    Column("enty_st", String(2)),
    Column("enty_zip4", String(10)),
    Column("ctrib_emp", String(120)),
    Column("ctrib_occ", String(70)),
    Column("amount", Numeric(15, 2)),
    Column("receipt_dt", Date),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

s498_cd = Table(
    "s498_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("cmte_id", String(20)),
    Column("payor_naml", String(120)),
    Column("payor_namf", String(30)),
    Column("payor_namt", String(40)),
    Column("payor_nams", String(30)),
    Column("payor_city", String(40)),
    Column("payor_st", String(2)),
    Column("payor_zip4", String(10)),
    Column("expn_date", Date),
    Column("expn_amt", Numeric(15, 2)),
    Column("expn_dscr", Text),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

f495p2 = Table(
    "f495p2", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("elect_date", Date),
    Column("electjuris", String(30)),
    Column("contribamt", Numeric(15, 2)),
)

f501_502 = Table(
    "f501_502", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("filer_id", String(20)),
    Column("committee_id", String(20)),
    Column("entity_cd", String(10)),
    Column("report_num", Integer),
    Column("rpt_date", Date),
    Column("stmnt_type", String(20)),
    Column("from_date", Date),
    Column("thru_date", Date),
    Column("elect_date", Date),
    Column("cand_naml", String(120)),
    Column("cand_namf", String(30)),
    Column("cand_namt", String(40)),
    Column("cand_nams", String(30)),
    Column("cand_city", String(40)),
    Column("cand_st", String(2)),
    Column("cand_zip4", String(10)),
    Column("cand_office", String(60)),
    Column("cand_dist", Integer),
    Column("cand_county", String(30)),
    Column("cand_party", String(10)),
    Column("cand_election_type", String(30)),
    Column("cand_yr", Integer),
    Column("party", String(10)),
    Column("treas_naml", String(120)),
    Column("treas_namf", String(30)),
    Column("treas_namt", String(40)),
    Column("treas_nams", String(30)),
    Column("treas_city", String(40)),
    Column("treas_st", String(2)),
    Column("treas_zip4", String(10)),
    Column("treas_phone", String(20)),
    Column("incrb_dt", Date),
    Column("incrb_state", String(20)),
    Column("auth_naml", String(120)),
    Column("auth_namf", String(30)),
    Column("auth_namt", String(40)),
    Column("auth_nams", String(30)),
    Column("auth_city", String(40)),
    Column("auth_st", String(2)),
    Column("auth_zip4", String(10)),
    Column("auth_phone", String(20)),
    Column("coverage_type", String(20)),
    Column("filing_status", String(20)),
)

f690p2 = Table(
    "f690p2", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("exec_date", Date),
    Column("from_date", Date),
    Column("thru_date", Date),
    Column("chg_parts", Text),
    Column("chg_sects", Text),
    Column("amend_txt1", Text),
)

# =============================================================================
# 8. Expenditure & Payment Tables
# =============================================================================

latt_cd = Table(
    "latt_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("recip_naml", String(120)),
    Column("recip_namf", String(30)),
    Column("recip_namt", String(40)),
    Column("recip_nams", String(30)),
    Column("recip_city", String(40)),
    Column("recip_st", String(2)),
    Column("recip_zip4", String(10)),
    Column("pmt_date", Date),
    Column("pmt_amt", Numeric(15, 2)),
    Column("pmt_type", String(10)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

lpay_cd = Table(
    "lpay_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("emplr_naml", String(120)),
    Column("emplr_namf", String(30)),
    Column("emplr_namt", String(40)),
    Column("emplr_nams", String(30)),
    Column("emplr_city", String(40)),
    Column("emplr_st", String(2)),
    Column("emplr_zip4", String(10)),
    Column("emplr_phon", String(20)),
    Column("loan_id", String(30)),
    Column("repmt_amt", Numeric(15, 2)),
    Column("repmt_dt", Date),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

lccm_cd = Table(
    "lccm_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("entity_cd", String(10)),
    Column("recip_naml", String(120)),
    Column("recip_namf", String(30)),
    Column("recip_namt", String(40)),
    Column("recip_nams", String(30)),
    Column("recip_city", String(40)),
    Column("recip_st", String(2)),
    Column("recip_zip4", String(10)),
    Column("recip_id", String(30)),
    Column("pmt_date", Date),
    Column("pmt_amt", Numeric(15, 2)),
    Column("pmt_type", String(10)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

lexp_cd = Table(
    "lexp_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("recsubtype", String(10)),
    Column("entity_cd", String(10)),
    Column("payee_naml", String(120)),
    Column("payee_namf", String(30)),
    Column("payee_namt", String(40)),
    Column("payee_nams", String(30)),
    Column("payee_city", String(40)),
    Column("payee_st", String(2)),
    Column("payee_zip4", String(10)),
    Column("payee_phon", String(20)),
    Column("payee_fax", String(20)),
    Column("payee_email", String(100)),
    Column("expn_date", Date),
    Column("expn_amt", Numeric(15, 2)),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

loth_cd = Table(
    "loth_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("tran_id", String(30)),
    Column("firm_name", String(120)),
    Column("firm_city", String(40)),
    Column("firm_st", String(2)),
    Column("firm_zip4", String(10)),
    Column("firm_phon", String(20)),
    Column("subj_naml", String(120)),
    Column("subj_namf", String(30)),
    Column("subj_namt", String(40)),
    Column("subj_nams", String(30)),
    Column("subj_city", String(40)),
    Column("subj_st", String(2)),
    Column("subj_zip4", String(10)),
    Column("subj_phon", String(20)),
    Column("subj_fax", String(20)),
    Column("subj_email", String(100)),
    Column("amount", Numeric(15, 2)),
    Column("actv_dt", Date),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

# =============================================================================
# 9. Lobbying Tables
# =============================================================================

lemp_cd = Table(
    "lemp_cd", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("line_item", Integer),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("client_id", String(20)),
    Column("cli_naml", String(120)),
    Column("cli_namf", String(30)),
    Column("cli_namt", String(40)),
    Column("cli_nams", String(30)),
    Column("cli_city", String(40)),
    Column("cli_st", String(2)),
    Column("cli_zip4", String(10)),
    Column("cli_phon", String(20)),
    Column("eff_date", Date),
    Column("termination_dt", Date),
    Column("lby_reg_id", String(30)),
    Column("lby_reg_name", String(120)),
    Column("lby_firm_id", String(20)),
    Column("lby_firm_name", String(120)),
    Column("lby_firm_city", String(40)),
    Column("lby_firm_st", String(2)),
    Column("lby_firm_zip4", String(10)),
    Column("lby_firm_phon", String(20)),
    Column("lby_firm_fax", String(20)),
    Column("lby_firm_email", String(100)),
    Column("activities_desc", Text),
    Column("memo_code", String(10)),
    Column("memo_refno", String(30)),
    Column("filer_id", String(20)),
)

lobby_amendments = Table(
    "lobby_amendments", metadata,
    Column("filing_id", String(30)),
    Column("amend_id", String(30)),
    Column("rec_type", String(10)),
    Column("form_type", String(10)),
    Column("exec_date", Date),
    Column("from_date", Date),
    Column("thru_date", Date),
    Column("add_l_cb", String(5)),
    Column("add_l_eff", String(10)),
    Column("a_l_naml", String(120)),
    Column("a_l_namf", String(30)),
    Column("a_l_namt", String(40)),
    Column("a_l_nams", String(30)),
    Column("del_l_cb", String(5)),
    Column("del_l_eff", String(10)),
    Column("d_l_naml", String(120)),
    Column("d_l_namf", String(30)),
    Column("d_l_namt", String(40)),
    Column("d_l_nams", String(30)),
    Column("mod_l_cb", String(5)),
    Column("mod_l_eff", String(10)),
    Column("m_l_naml", String(120)),
    Column("m_l_namf", String(30)),
    Column("m_l_namt", String(40)),
    Column("m_l_nams", String(30)),
    Column("amend_desc", Text),
    Column("filer_id", String(20)),
    Column("principal_id", String(20)),
    Column("principal_name", String(120)),
)

lobbying_chg_log = Table(
    "lobbying_chg_log", metadata,
    Column("filer_id", String(20)),
    Column("change_no", Integer, nullable=False),
    Column("session_id", Integer),
    Column("log_dt", DateTime),
    Column("filer_type", String(20)),
    Column("correction_flg", Boolean),
    Column("action", String(30)),
    Column("attribute_changed", String(60)),
    Column("ethics_dt", Date),
    Column("interests", Text),
    Column("filer_full_name", String(120)),
    Column("filer_city", String(40)),
    Column("filer_st", String(2)),
    Column("filer_zip", String(10)),
    Column("filer_phone", String(20)),
)

lobbyist_contributions = Table(
    "lobbyist_contributions", metadata,
    Column("filer_id", String(20)),
    Column("filing_period_start_dt", Date),
    Column("filing_period_end_dt", Date),
    Column("contribution_dt", Date),
    Column("recipient_name", String(120)),
    Column("recipient_id", String(30)),
    Column("amount", Numeric(15, 2)),
    Column("source_period", String(10)),
)

lobbyist_employers = Table(
    "lobbyist_employers", metadata,
    Column("employer_id", String(30)),
    Column("session_id", Integer),
    Column("employer_name", String(120)),
    Column("current_qtr_amt", Numeric(15, 2)),
    Column("session_total_amt", Numeric(15, 2)),
    Column("contributor_id", String(30)),
    Column("interest_cd", String(20)),
    Column("interest_name", String(120)),
    Column("session_yr_1", Numeric(15, 2)),
    Column("session_yr_2", Numeric(15, 2)),
    Column("yr_1_ytd_amt", Numeric(15, 2)),
    Column("yr_2_ytd_amt", Numeric(15, 2)),
    Column("qtr_1", Numeric(15, 2)),
    Column("qtr_2", Numeric(15, 2)),
    Column("qtr_3", Numeric(15, 2)),
    Column("qtr_4", Numeric(15, 2)),
    Column("qtr_5", Numeric(15, 2)),
    Column("yr_1_amt", Numeric(15, 2)),
    Column("yr_2_amt", Numeric(15, 2)),
    Column("total_amt", Numeric(15, 2)),
    Column("termination_dt", Date),
)

lobbyist_employer_firms = Table(
    "lobbyist_employer_firms", metadata,
    Column("employer_id", String(30)),
    Column("firm_id", String(20)),
    Column("firm_name", String(120)),
    Column("session_id", Integer),
    Column("termination_dt", Date),
)

lobbyist_employer_lobbyist = Table(
    "lobbyist_employer_lobbyist", metadata,
    Column("lobbyist_id", String(20)),
    Column("employer_id", String(30)),
    Column("lobbyist_last_name", String(60)),
    Column("lobbyist_first_name", String(60)),
    Column("employer_name", String(120)),
    Column("session_id", Integer),
)

lobbyist_firms = Table(
    "lobbyist_firms", metadata,
    Column("firm_id", String(20)),
    Column("session_id", Integer),
    Column("firm_name", String(120)),
    Column("current_qtr_amt", Numeric(15, 2)),
    Column("session_total_amt", Numeric(15, 2)),
    Column("contributor_id", String(30)),
    Column("session_yr_1", Numeric(15, 2)),
    Column("session_yr_2", Numeric(15, 2)),
    Column("yr_1_ytd_amt", Numeric(15, 2)),
    Column("yr_2_ytd_amt", Numeric(15, 2)),
    Column("qtr_1", Numeric(15, 2)),
    Column("qtr_2", Numeric(15, 2)),
    Column("qtr_3", Numeric(15, 2)),
    Column("qtr_4", Numeric(15, 2)),
    Column("qtr_5", Numeric(15, 2)),
    Column("yr_1_amt", Numeric(15, 2)),
    Column("yr_2_amt", Numeric(15, 2)),
    Column("total_amt", Numeric(15, 2)),
)

lobbyist_firm_employer = Table(
    "lobbyist_firm_employer", metadata,
    Column("firm_id", String(20)),
    Column("filing_id", String(30)),
    Column("filing_sequence", Integer),
    Column("firm_name", String(120)),
    Column("employer_name", String(120)),
    Column("rpt_start", Date),
    Column("rpt_end", Date),
    Column("per_total", Numeric(15, 2)),
    Column("cum_total", Numeric(15, 2)),
    Column("lby_actvty", Text),
    Column("ext_lby_actvty", Text),
)

lobbyist_firm_lobbyist = Table(
    "lobbyist_firm_lobbyist", metadata,
    Column("lobbyist_id", String(20)),
    Column("firm_id", String(20)),
    Column("lobbyist_last_name", String(60)),
    Column("lobbyist_first_name", String(60)),
    Column("firm_name", String(120)),
    Column("session_id", Integer),
)

# =============================================================================
# 10. Ballot Measure Tables
# =============================================================================

ballot_measures = Table(
    "ballot_measures", metadata,
    Column("election_date", Date, nullable=False),
    Column("filer_id", String(20)),
    Column("measure_no", String(20), nullable=False),
    Column("measure_name", Text, nullable=False),
    Column("measure_short_name", String(200)),
    Column("jurisdiction", String(60)),
)

# =============================================================================
# 11. Filing Calendar
# =============================================================================

filing_calendar = Table(
    "filing_calendar", metadata,
    Column("election_date", Date, nullable=False),
    Column("election_type", String(30), nullable=False),
    Column("filing_type", String(30)),
    Column("deadline", Date, nullable=False),
    Column("grace_period_days", Integer, default=0),
    Column("extended_deadline", Date),
    Column("source", String(50)),
    Column("notes", Text),
)

# =============================================================================
# 12. Entity Resolution Tables
# =============================================================================

entity = Table(
    "entity", metadata,
    Column("entity_id", Integer, nullable=False, primary_key=True),
    Column("naml", String(120), nullable=False),
    Column("namf", String(30)),
    Column("namt", String(40)),
    Column("nams", String(30)),
    Column("moniker", String(30)),
    Column("namm", String(30)),
    Column("fullname", String(300)),
    Column("entity_type", String(20), default="unknown"),
    Column("source_filer_id", String(20)),
    Column("created_at", DateTime, default=None),
    Column("updated_at", DateTime, default=None),
    Column("resolved_by", Integer),
)

entity_alias = Table(
    "entity_alias", metadata,
    Column("alias_id", Integer, nullable=False, primary_key=True),
    Column("entity_id", Integer, nullable=False),
    Column("alias_name", String(300), nullable=False),
    Column("source_filer_id", String(20)),
    Column("source_table", String(30)),
    Column("created_at", DateTime, default=None),
)

entity_merge_queue = Table(
    "entity_merge_queue", metadata,
    Column("queue_id", Integer, nullable=False, primary_key=True),
    Column("entity_a_id", Integer),
    Column("entity_b_id", Integer),
    Column("match_score", Numeric(5, 4)),
    Column("match_method", String(30)),
    Column("status", String(20), default="pending"),
    Column("reviewed_by", String(100)),
    Column("reviewed_at", DateTime),
    Column("notes", Text),
    Column("created_at", DateTime, default=None),
)

# =============================================================================
# 13. ETL Infrastructure Tables
# =============================================================================

source_info = Table(
    "source_info", metadata,
    Column("source_id", Integer, nullable=False, primary_key=True),
    Column("source", String(30), default="calaccess"),
    Column("zip_checksum", String(64), nullable=False),
    Column("zip_size_bytes", Integer),
    Column("load_date", Date, default=None),
    Column("load_started_at", DateTime, default=None),
    Column("load_completed_at", DateTime),
    Column("tables_loaded", Integer),
    Column("rows_loaded", Integer),
    Column("notes", Text),
)

load_checkpoint = Table(
    "load_checkpoint", metadata,
    Column("checkpoint_id", Integer, nullable=False, primary_key=True),
    Column("table_name", String(50), nullable=False),
    Column("source", String(30), default="calaccess"),
    Column("file_hash", String(64), nullable=False),
    Column("source_file", String(200)),
    Column("processed_date", DateTime, default=None),
    Column("rows_processed", Integer),
    Column("notes", Text),
)

etl_dead_letter = Table(
    "etl_dead_letter", metadata,
    Column("dead_letter_id", Integer, nullable=False, primary_key=True),
    Column("table_name", String(50)),
    Column("source_file", String(200)),
    Column("row_data", Text, nullable=False),
    Column("error_message", Text, nullable=False),
    Column("error_code", String(30)),
    Column("created_at", DateTime, default=None),
    Column("resolved_at", DateTime),
    Column("resolved_by", String(100)),
)
