"""Table definitions registry for CAL-ACCESS data sources.

Maps CAL-ACCESS TSV files (as found in the official dbwebexport.zip) to
their table codes, descriptions, conflict columns, and type coercions.

Aligned to the REAL SOS export (verified 2026-07 against
CalAccess/DATA/*.TSV + the official data-model document):
  - tsv_files use the actual upper-case .TSV names under CalAccess/DATA/
  - conflict_columns match the primary keys in migrations/0001
  - conflict_columns=None marks surrogate-PK tables loaded via
    truncate + insert (no natural key in the export)
Generated block: do not edit by hand — run .dev/gen_ddl.py and re-apply.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class TableDefinition:
    """Schema-level definition for one CAL-ACCESS table.

    Attributes:
        code: Short table code (e.g. "RCPT_CD").
        description: Human-readable description.
        category: One of "fact", "dimension", "disclosure", "lobbying", "other".
        tsv_files: List of TSV filenames in dbwebexport.zip.
        conflict_columns: Columns forming the unique key for upsert.
        type_coercions: Optional {column: "numeric"|"date"|"integer"|"timestamp"}.
        required_columns: Columns that must be non-null for a valid row.
        skip_columns: Internal columns to exclude from the insert.
        partition_by_date: If True, the table uses PostgreSQL partitioning.
        date_column: The DATE/TIMESTAMPTZ column used for partitioning.
    """

    code: str
    description: str
    category: str = "other"
    tsv_files: list[str] | None = None
    conflict_columns: list[str] | None = None
    type_coercions: dict[str, str] | None = None
    required_columns: list[str] | None = None
    skip_columns: list[str] | None = None
    partition_by_date: bool = False
    date_column: str | None = None
    source: str | None = None  # "tsv" or "scrape" — data loading method



# Generated by .dev/gen_ddl.py — column sets/types aligned to the real
# CAL-ACCESS export (2026-07). Do not edit by hand; regenerate instead.

TABLE_DEFINITIONS: dict[str, TableDefinition] = {
    "ACRONYMS_CD": TableDefinition(
        code="ACRONYMS_CD",
        description="Filer acronyms (abbreviation -> meaning)",
        category="dimension",
        tsv_files=["CalAccess/DATA/ACRONYMS_CD.TSV"],
        conflict_columns=["acronym"],
        type_coercions={"effect_dt": "timestamp"},
    ),
    "ADDRESS_CD": TableDefinition(
        code="ADDRESS_CD",
        description="Address master (unique address records)",
        category="dimension",
        tsv_files=["CalAccess/DATA/ADDRESS_CD.TSV"],
        conflict_columns=["adrid"],
        type_coercions={"adrid": "integer"},
    ),
    "BALLOT_MEASURES_CD": TableDefinition(
        code="BALLOT_MEASURES_CD",
        description="Ballot measures filed by filers",
        category="dimension",
        tsv_files=["CalAccess/DATA/BALLOT_MEASURES_CD.TSV"],
        conflict_columns=["filer_id"],
        type_coercions={"election_date": "timestamp", "filer_id": "integer"},
    ),
    "CVR2_CAMPAIGN_DISCLOSURE_CD": TableDefinition(
        code="CVR2_CAMPAIGN_DISCLOSURE_CD",
        description="CVR/2 campaign disclosure — registration & summary",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR2_CAMPAIGN_DISCLOSURE_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer"},
    ),
    "CVR2_LOBBY_DISCLOSURE_CD": TableDefinition(
        code="CVR2_LOBBY_DISCLOSURE_CD",
        description="CVR/2 lobbying disclosure",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR2_LOBBY_DISCLOSURE_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"amend_id": "integer", "filing_id": "integer", "line_item": "integer"},
    ),
    "CVR2_REGISTRATION_CD": TableDefinition(
        code="CVR2_REGISTRATION_CD",
        description="CVR/2 committee registration details",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR2_REGISTRATION_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer"},
    ),
    "CVR2_SO_CD": TableDefinition(
        code="CVR2_SO_CD",
        description="CVR/2 summary of receipts/disbursements",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR2_SO_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer"},
    ),
    "CVR3_VERIFICATION_INFO_CD": TableDefinition(
        code="CVR3_VERIFICATION_INFO_CD",
        description="CVR/3 candidate verification info",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR3_VERIFICATION_INFO_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "sig_date": "timestamp"},
    ),
    "CVR_CAMPAIGN_DISCLOSURE_CD": TableDefinition(
        code="CVR_CAMPAIGN_DISCLOSURE_CD",
        description="CVR campaign disclosure — registration & summary",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR_CAMPAIGN_DISCLOSURE_CD.TSV"],
        conflict_columns=["amend_id", "filing_id"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "rpt_date": "timestamp", "from_date": "timestamp", "thru_date": "timestamp", "elect_date": "timestamp", "rptfromdt": "timestamp", "rptthrudt": "timestamp"},
    ),
    "CVR_E530_CD": TableDefinition(
        code="CVR_E530_CD",
        description="CVR/E530 special election expenditure report",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR_E530_CD.TSV"],
        conflict_columns=["amend_id", "filing_id"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "rpt_date": "timestamp", "district_cd": "integer", "office_cd": "integer", "pmnt_dt": "timestamp", "pmnt_amount": "numeric"},
    ),
    "CVR_F470_CD": TableDefinition(
        code="CVR_F470_CD",
        description="CVR/F-470 candidate filing statement",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR_F470_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "rpt_date": "timestamp", "elect_date": "timestamp", "date_1000": "timestamp"},
    ),
    "CVR_LOBBY_DISCLOSURE_CD": TableDefinition(
        code="CVR_LOBBY_DISCLOSURE_CD",
        description="CVR lobbying disclosure (lobbyist registrations)",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR_LOBBY_DISCLOSURE_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "rpt_date": "timestamp", "from_date": "timestamp", "thru_date": "timestamp", "cum_beg_dt": "timestamp", "sig_date": "timestamp"},
    ),
    "CVR_REGISTRATION_CD": TableDefinition(
        code="CVR_REGISTRATION_CD",
        description="CVR committee registration details",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR_REGISTRATION_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "rpt_date": "timestamp", "qual_date": "timestamp", "eff_date": "timestamp", "sig_date": "timestamp", "complet_dt": "timestamp"},
    ),
    "CVR_SO_CD": TableDefinition(
        code="CVR_SO_CD",
        description="CVR summary of receipts/disbursements",
        category="disclosure",
        tsv_files=["CalAccess/DATA/CVR_SO_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "rpt_date": "timestamp", "qualfy_dt": "timestamp", "term_date": "timestamp", "acct_opendt": "timestamp", "smcont_qualdt": "timestamp"},
    ),
    "DEBT_CD": TableDefinition(
        code="DEBT_CD",
        description="Debts owed by committee (detail lines)",
        category="fact",
        tsv_files=["CalAccess/DATA/DEBT_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "beg_bal": "numeric", "amt_incur": "numeric", "amt_paid": "numeric", "end_bal": "numeric"},
    ),
    "EFS_FILING_LOG_CD": TableDefinition(
        code="EFS_FILING_LOG_CD",
        description="Electronic filing system activity log",
        category="dimension",
        tsv_files=["CalAccess/DATA/EFS_FILING_LOG_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"filing_date": "timestamp"},
    ),
    "EXPN_CD": TableDefinition(
        code="EXPN_CD",
        description="Expenditures — payments to vendors, goods, services",
        category="fact",
        tsv_files=["CalAccess/DATA/EXPN_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "expn_date": "timestamp", "amount": "numeric", "cum_ytd": "numeric", "cum_oth": "numeric"},
    ),
    "F495P2_CD": TableDefinition(
        code="F495P2_CD",
        description="Form 495 (P2) — candidate acceptance statement",
        category="fact",
        tsv_files=["CalAccess/DATA/F495P2_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "elect_date": "timestamp", "contribamt": "numeric"},
    ),
    "F501_502_CD": TableDefinition(
        code="F501_502_CD",
        description="Forms 501/502 — candidate/committee financial reports",
        category="fact",
        tsv_files=["CalAccess/DATA/F501_502_CD.TSV"],
        conflict_columns=["amend_id", "filing_id"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "entity_cd": "integer", "rpt_date": "timestamp", "stmt_type": "integer", "from_date": "timestamp", "thru_date": "timestamp", "elect_date": "timestamp", "moniker_pos": "integer", "office_cd": "integer", "juris_cd": "integer", "yr_of_elec": "integer", "elec_type": "integer", "execute_dt": "timestamp", "acct_op_dt": "timestamp", "party_cd": "integer", "district_cd": "integer", "did_exceed_dt": "timestamp"},
    ),
    "F690P2_CD": TableDefinition(
        code="F690P2_CD",
        description="Form 690 (P2) — ballot measure committee report",
        category="fact",
        tsv_files=["CalAccess/DATA/F690P2_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "exec_date": "timestamp", "from_date": "timestamp", "thru_date": "timestamp"},
    ),
    "FILERNAME_CD": TableDefinition(
        code="FILERNAME_CD",
        description="Filer names and addresses (current state; no natural key -> surrogate)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILERNAME_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"filer_id": "integer", "effect_dt": "timestamp"},
    ),
    "FILERS_CD": TableDefinition(
        code="FILERS_CD",
        description="Filer master (all filer IDs)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILERS_CD.TSV"],
        conflict_columns=["filer_id"],
        type_coercions={"filer_id": "integer"},
    ),
    "FILER_ACRONYMS_CD": TableDefinition(
        code="FILER_ACRONYMS_CD",
        description="Filer-to-acronym mapping",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_ACRONYMS_CD.TSV"],
        conflict_columns=["acronym", "filer_id"],
        type_coercions={"filer_id": "integer"},
    ),
    "FILER_ADDRESS_CD": TableDefinition(
        code="FILER_ADDRESS_CD",
        description="Filer-to-address mapping (historical)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_ADDRESS_CD.TSV"],
        conflict_columns=["adrid", "filer_id"],
        type_coercions={"filer_id": "integer", "adrid": "integer", "effect_dt": "timestamp", "add_type": "integer", "session_id": "integer"},
    ),
    "FILER_ETHICS_CLASS_CD": TableDefinition(
        code="FILER_ETHICS_CLASS_CD",
        description="Filer ethics class assignments",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_ETHICS_CLASS_CD.TSV"],
        conflict_columns=["ethics_date", "filer_id", "session_id"],
        type_coercions={"filer_id": "integer", "session_id": "integer", "ethics_date": "timestamp"},
    ),
    "FILER_FILINGS_CD": TableDefinition(
        code="FILER_FILINGS_CD",
        description="Filer-to-filing mapping (which filers appear on each filing)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_FILINGS_CD.TSV"],
        conflict_columns=["filer_id", "filing_id", "filing_sequence", "form_id"],
        type_coercions={"filer_id": "integer", "filing_id": "integer", "period_id": "integer", "filing_sequence": "integer", "filing_date": "timestamp", "stmnt_type": "integer", "stmnt_status": "integer", "session_id": "integer", "special_audit": "integer", "fine_audit": "integer", "rpt_start": "timestamp", "rpt_end": "timestamp", "rpt_date": "timestamp"},
    ),
    "FILER_INTERESTS_CD": TableDefinition(
        code="FILER_INTERESTS_CD",
        description="Filer declared interests",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_INTERESTS_CD.TSV"],
        conflict_columns=["effect_date", "filer_id", "interest_cd", "session_id"],
        type_coercions={"filer_id": "integer", "session_id": "integer", "interest_cd": "integer", "effect_date": "timestamp"},
    ),
    "FILER_LINKS_CD": TableDefinition(
        code="FILER_LINKS_CD",
        description="Filer-to-filer links (candidate/committee relationships)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_LINKS_CD.TSV"],
        conflict_columns=["active_flg", "filer_id_a", "filer_id_b", "link_type", "session_id"],
        type_coercions={"filer_id_a": "integer", "filer_id_b": "integer", "session_id": "integer", "link_type": "integer", "effect_dt": "timestamp", "termination_dt": "timestamp"},
    ),
    "FILER_STATUS_TYPES_CD": TableDefinition(
        code="FILER_STATUS_TYPES_CD",
        description="Filer status type reference",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_STATUS_TYPES_CD.TSV"],
        conflict_columns=["status_type"],
        type_coercions={},
    ),
    "FILER_TO_FILER_TYPE_CD": TableDefinition(
        code="FILER_TO_FILER_TYPE_CD",
        description="Filer-to-filer-type assignment (historical)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_TO_FILER_TYPE_CD.TSV"],
        conflict_columns=["effect_dt", "filer_id", "filer_type", "session_id"],
        type_coercions={"filer_id": "integer", "filer_type": "integer", "race": "integer", "session_id": "integer", "category": "integer", "category_type": "integer", "sub_category": "integer", "effect_dt": "timestamp", "sub_category_type": "integer", "election_type": "integer", "nyq_dt": "timestamp", "party_cd": "integer", "county_cd": "integer", "district_cd": "integer"},
    ),
    "FILER_TYPES_CD": TableDefinition(
        code="FILER_TYPES_CD",
        description="Filer type reference (committee/candidate/lobbyist...)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_TYPES_CD.TSV"],
        conflict_columns=["filer_type"],
        type_coercions={"filer_type": "integer", "grp_type": "integer", "grace_period": "integer"},
    ),
    "FILER_TYPE_PERIODS_CD": TableDefinition(
        code="FILER_TYPE_PERIODS_CD",
        description="Filer-type to filing-period assignment (empty in export)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_TYPE_PERIODS_CD.TSV"],
        conflict_columns=["election_type", "filer_type", "period_id"],
        type_coercions={"election_type": "integer", "filer_type": "integer", "period_id": "integer"},
    ),
    "FILER_XREF_CD": TableDefinition(
        code="FILER_XREF_CD",
        description="Filer cross-reference (alternate IDs)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILER_XREF_CD.TSV"],
        conflict_columns=["filer_id", "xref_id"],
        type_coercions={"filer_id": "integer", "effect_dt": "timestamp"},
    ),
    "FILINGS_CD": TableDefinition(
        code="FILINGS_CD",
        description="Filing master (all filing IDs)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILINGS_CD.TSV"],
        conflict_columns=["filing_id"],
        type_coercions={"filing_id": "integer", "filing_type": "integer"},
    ),
    "FILING_PERIOD_CD": TableDefinition(
        code="FILING_PERIOD_CD",
        description="Filing period calendar (periods, types, deadlines)",
        category="dimension",
        tsv_files=["CalAccess/DATA/FILING_PERIOD_CD.TSV"],
        conflict_columns=["period_id"],
        type_coercions={"period_id": "integer", "start_date": "timestamp", "end_date": "timestamp", "period_type": "integer", "per_grp_type": "integer", "deadline": "timestamp"},
    ),
    "GROUP_TYPES_CD": TableDefinition(
        code="GROUP_TYPES_CD",
        description="Lobbying interest group type reference",
        category="dimension",
        tsv_files=["CalAccess/DATA/GROUP_TYPES_CD.TSV"],
        conflict_columns=["grp_id"],
        type_coercions={"grp_id": "integer"},
    ),
    "HDR_CD": TableDefinition(
        code="HDR_CD",
        description="Filing header records (form type, filer, submission info)",
        category="fact",
        tsv_files=["CalAccess/DATA/HDR_CD.TSV"],
        conflict_columns=["amend_id", "filing_id"],
        type_coercions={"filing_id": "integer", "amend_id": "integer"},
    ),
    "HEADER_CD": TableDefinition(
        code="HEADER_CD",
        description="Form header definitions (form metadata)",
        category="dimension",
        tsv_files=["CalAccess/DATA/HEADER_CD.TSV"],
        conflict_columns=["form_id", "line_number", "rec_type"],
        type_coercions={"line_number": "integer", "column_a": "numeric", "column_b": "numeric", "column_c": "numeric", "show_c": "integer", "show_b": "integer"},
    ),
    "IMAGE_LINKS_CD": TableDefinition(
        code="IMAGE_LINKS_CD",
        description="Links to scanned image documents",
        category="dimension",
        tsv_files=["CalAccess/DATA/IMAGE_LINKS_CD.TSV"],
        conflict_columns=["img_id", "img_link_id"],
        type_coercions={"img_link_id": "integer", "img_link_type": "integer", "img_id": "integer", "img_type": "integer", "img_dt": "timestamp"},
    ),
    "LATT_CD": TableDefinition(
        code="LATT_CD",
        description="Lobbying activities — attorney lobbying detail",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LATT_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "pmt_date": "timestamp", "amount": "numeric", "cum_amt": "numeric", "cumbeg_dt": "timestamp"},
    ),
    "LCCM_CD": TableDefinition(
        code="LCCM_CD",
        description="Lobbying — client committee detail",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LCCM_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "ctrib_date": "timestamp", "amount": "numeric"},
    ),
    "LEGISLATIVE_SESSIONS_CD": TableDefinition(
        code="LEGISLATIVE_SESSIONS_CD",
        description="Legislative session reference",
        category="dimension",
        tsv_files=["CalAccess/DATA/LEGISLATIVE_SESSIONS_CD.TSV"],
        conflict_columns=["session_id"],
        type_coercions={"session_id": "integer", "begin_date": "timestamp", "end_date": "timestamp"},
    ),
    "LEMP_CD": TableDefinition(
        code="LEMP_CD",
        description="Lobbying employment — lobbyist compensation detail",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LEMP_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "eff_date": "timestamp"},
    ),
    "LEXP_CD": TableDefinition(
        code="LEXP_CD",
        description="Lobbying expenditures detail",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LEXP_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "expn_date": "timestamp", "amount": "numeric"},
    ),
    "LOAN_CD": TableDefinition(
        code="LOAN_CD",
        description="Loans received by committee (detail lines)",
        category="fact",
        tsv_files=["CalAccess/DATA/LOAN_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "loan_date1": "timestamp", "loan_date2": "timestamp", "loan_amt1": "numeric", "loan_amt2": "numeric", "loan_amt3": "numeric", "loan_amt4": "numeric", "loan_amt5": "numeric", "loan_amt6": "numeric", "loan_amt7": "numeric", "loan_amt8": "numeric"},
    ),
    "LOBBYING_CHG_LOG_CD": TableDefinition(
        code="LOBBYING_CHG_LOG_CD",
        description="Lobbying registration change log",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYING_CHG_LOG_CD.TSV"],
        conflict_columns=["change_no", "filer_id"],
        type_coercions={"filer_id": "integer", "change_no": "integer", "session_id": "integer", "log_dt": "timestamp", "filer_type": "integer", "ethics_dt": "timestamp", "entity_type": "integer", "entity_id": "integer", "effect_dt": "timestamp"},
    ),
    "LOBBYIST_CONTRIBUTIONS1_CD": TableDefinition(
        code="LOBBYIST_CONTRIBUTIONS1_CD",
        description="Lobbyist contributions to candidates (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_CONTRIBUTIONS1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"filer_id": "integer", "filing_period_start_dt": "timestamp", "filing_period_end_dt": "timestamp", "contribution_dt": "timestamp", "recipient_id": "integer", "amount": "numeric"},
    ),
    "LOBBYIST_CONTRIBUTIONS2_CD": TableDefinition(
        code="LOBBYIST_CONTRIBUTIONS2_CD",
        description="Lobbyist contributions to candidates (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_CONTRIBUTIONS2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"filer_id": "integer", "filing_period_start_dt": "timestamp", "filing_period_end_dt": "timestamp", "contribution_dt": "timestamp", "recipient_id": "integer", "amount": "numeric"},
    ),
    "LOBBYIST_CONTRIBUTIONS3_CD": TableDefinition(
        code="LOBBYIST_CONTRIBUTIONS3_CD",
        description="Lobbyist contributions to candidates (history part 3)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_CONTRIBUTIONS3_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"filer_id": "integer", "filing_period_start_dt": "timestamp", "filing_period_end_dt": "timestamp", "contribution_dt": "timestamp", "recipient_id": "integer", "amount": "numeric"},
    ),
    "LOBBYIST_EMPLOYER1_CD": TableDefinition(
        code="LOBBYIST_EMPLOYER1_CD",
        description="Lobbying — employer summary (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMPLOYER1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"employer_id": "integer", "session_id": "integer", "current_qtr_amt": "numeric", "session_total_amt": "numeric", "contributor_id": "integer", "interest_cd": "integer", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric"},
    ),
    "LOBBYIST_EMPLOYER2_CD": TableDefinition(
        code="LOBBYIST_EMPLOYER2_CD",
        description="Lobbying — employer summary (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMPLOYER2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"employer_id": "integer", "session_id": "integer", "current_qtr_amt": "numeric", "session_total_amt": "numeric", "contributor_id": "integer", "interest_cd": "integer", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric"},
    ),
    "LOBBYIST_EMPLOYER3_CD": TableDefinition(
        code="LOBBYIST_EMPLOYER3_CD",
        description="Lobbying — employer summary (history part 3)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMPLOYER3_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"employer_id": "integer", "session_id": "integer", "current_qtr_amt": "numeric", "session_total_amt": "numeric", "contributor_id": "integer", "interest_cd": "integer", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric"},
    ),
    "LOBBYIST_EMPLOYER_FIRMS1_CD": TableDefinition(
        code="LOBBYIST_EMPLOYER_FIRMS1_CD",
        description="Lobbyist employer-firm mapping (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMPLOYER_FIRMS1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"employer_id": "integer", "firm_id": "integer", "session_id": "integer", "termination_dt": "timestamp"},
    ),
    "LOBBYIST_EMPLOYER_FIRMS2_CD": TableDefinition(
        code="LOBBYIST_EMPLOYER_FIRMS2_CD",
        description="Lobbyist employer-firm mapping (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMPLOYER_FIRMS2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"employer_id": "integer", "firm_id": "integer", "session_id": "integer", "termination_dt": "timestamp"},
    ),
    "LOBBYIST_EMPLOYER_HISTORY_CD": TableDefinition(
        code="LOBBYIST_EMPLOYER_HISTORY_CD",
        description="Lobbyist employer history (empty in export)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMPLOYER_HISTORY_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"contributor_id": "integer", "current_qtr_amt": "numeric", "employer_id": "integer", "interest_cd": "integer", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric", "session_id": "integer", "session_total_amt": "numeric", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric"},
    ),
    "LOBBYIST_EMP_LOBBYIST1_CD": TableDefinition(
        code="LOBBYIST_EMP_LOBBYIST1_CD",
        description="Lobbyist employee-lobbyist mapping (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMP_LOBBYIST1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"lobbyist_id": "integer", "employer_id": "integer", "session_id": "integer"},
    ),
    "LOBBYIST_EMP_LOBBYIST2_CD": TableDefinition(
        code="LOBBYIST_EMP_LOBBYIST2_CD",
        description="Lobbyist employee-lobbyist mapping (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_EMP_LOBBYIST2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"lobbyist_id": "integer", "employer_id": "integer", "session_id": "integer"},
    ),
    "LOBBYIST_FIRM1_CD": TableDefinition(
        code="LOBBYIST_FIRM1_CD",
        description="Lobbying — firm summary (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"firm_id": "integer", "session_id": "integer", "current_qtr_amt": "numeric", "session_total_amt": "numeric", "contributor_id": "integer", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric"},
    ),
    "LOBBYIST_FIRM2_CD": TableDefinition(
        code="LOBBYIST_FIRM2_CD",
        description="Lobbying — firm summary (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"firm_id": "integer", "session_id": "integer", "current_qtr_amt": "numeric", "session_total_amt": "numeric", "contributor_id": "integer", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric"},
    ),
    "LOBBYIST_FIRM3_CD": TableDefinition(
        code="LOBBYIST_FIRM3_CD",
        description="Lobbying — firm summary (history part 3)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM3_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"firm_id": "integer", "session_id": "integer", "current_qtr_amt": "numeric", "session_total_amt": "numeric", "contributor_id": "integer", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric"},
    ),
    "LOBBYIST_FIRM_EMPLOYER1_CD": TableDefinition(
        code="LOBBYIST_FIRM_EMPLOYER1_CD",
        description="Lobbyist firm-employer mapping (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM_EMPLOYER1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"firm_id": "integer", "filing_id": "integer", "filing_sequence": "integer", "rpt_start": "timestamp", "rpt_end": "timestamp", "per_total": "numeric", "cum_total": "numeric"},
    ),
    "LOBBYIST_FIRM_EMPLOYER2_CD": TableDefinition(
        code="LOBBYIST_FIRM_EMPLOYER2_CD",
        description="Lobbyist firm-employer mapping (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM_EMPLOYER2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"firm_id": "integer", "filing_id": "integer", "filing_sequence": "integer", "rpt_start": "timestamp", "rpt_end": "timestamp", "per_total": "numeric", "cum_total": "numeric"},
    ),
    "LOBBYIST_FIRM_HISTORY_CD": TableDefinition(
        code="LOBBYIST_FIRM_HISTORY_CD",
        description="Lobbyist firm history (empty in export)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM_HISTORY_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"contributor_id": "integer", "current_qtr_amt": "numeric", "firm_id": "integer", "qtr_1": "numeric", "qtr_2": "numeric", "qtr_3": "numeric", "qtr_4": "numeric", "qtr_5": "numeric", "qtr_6": "numeric", "qtr_7": "numeric", "qtr_8": "numeric", "session_id": "integer", "session_total_amt": "numeric", "session_yr_1": "integer", "session_yr_2": "integer", "yr_1_ytd_amt": "numeric", "yr_2_ytd_amt": "numeric"},
    ),
    "LOBBYIST_FIRM_LOBBYIST1_CD": TableDefinition(
        code="LOBBYIST_FIRM_LOBBYIST1_CD",
        description="Lobbyist firm-lobbyist mapping (history part 1)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM_LOBBYIST1_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"lobbyist_id": "integer", "firm_id": "integer", "session_id": "integer"},
    ),
    "LOBBYIST_FIRM_LOBBYIST2_CD": TableDefinition(
        code="LOBBYIST_FIRM_LOBBYIST2_CD",
        description="Lobbyist firm-lobbyist mapping (history part 2)",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBYIST_FIRM_LOBBYIST2_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"lobbyist_id": "integer", "firm_id": "integer", "session_id": "integer"},
    ),
    "LOBBY_AMENDMENTS_CD": TableDefinition(
        code="LOBBY_AMENDMENTS_CD",
        description="Lobbying registration amendments",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOBBY_AMENDMENTS_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "exec_date": "timestamp", "from_date": "timestamp", "thru_date": "timestamp", "add_l_eff": "timestamp", "del_l_eff": "timestamp", "add_le_eff": "timestamp", "del_le_eff": "timestamp", "add_lf_eff": "timestamp", "del_lf_eff": "timestamp", "other_eff": "timestamp"},
    ),
    "LOOKUP_CODES_CD": TableDefinition(
        code="LOOKUP_CODES_CD",
        description="CAL-ACCESS lookup code reference",
        category="dimension",
        tsv_files=["CalAccess/DATA/LOOKUP_CODES_CD.TSV"],
        conflict_columns=["code_id", "code_type"],
        type_coercions={"code_type": "integer", "code_id": "integer"},
    ),
    "LOTH_CD": TableDefinition(
        code="LOTH_CD",
        description="Lobbying — other lobbying detail",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LOTH_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "pmt_date": "timestamp", "amount": "numeric", "cum_amt": "numeric"},
    ),
    "LPAY_CD": TableDefinition(
        code="LPAY_CD",
        description="Lobbying payments detail",
        category="lobbying",
        tsv_files=["CalAccess/DATA/LPAY_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "fees_amt": "numeric", "reimb_amt": "numeric", "advan_amt": "numeric", "per_total": "numeric", "cum_total": "numeric"},
    ),
    "NAMES_CD": TableDefinition(
        code="NAMES_CD",
        description="Name master (unique name records)",
        category="dimension",
        tsv_files=["CalAccess/DATA/NAMES_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"namid": "integer", "moniker_pos": "integer"},
    ),
    "RCPT_CD": TableDefinition(
        code="RCPT_CD",
        description="Receipts — contributions received by committees",
        category="fact",
        tsv_files=["CalAccess/DATA/RCPT_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "rcpt_date": "timestamp", "date_thru": "timestamp", "amount": "numeric", "cum_ytd": "numeric", "cum_oth": "numeric"},
    ),
    "RECEIVED_FILINGS_CD": TableDefinition(
        code="RECEIVED_FILINGS_CD",
        description="Received filings log",
        category="dimension",
        tsv_files=["CalAccess/DATA/RECEIVED_FILINGS_CD.TSV"],
        conflict_columns=None,  # surrogate id; truncate+insert load
        type_coercions={"filer_id": "integer", "received_date": "timestamp", "filing_id": "integer"},
    ),
    "REPORTS_CD": TableDefinition(
        code="REPORTS_CD",
        description="SOS report definitions reference",
        category="dimension",
        tsv_files=["CalAccess/DATA/REPORTS_CD.TSV"],
        conflict_columns=["rpt_id"],
        type_coercions={"rpt_id": "integer", "rpt_type": "integer", "parm_definition": "integer"},
    ),
    "S401_CD": TableDefinition(
        code="S401_CD",
        description="S-401 — committee summary of financial activity",
        category="fact",
        tsv_files=["CalAccess/DATA/S401_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "amount": "numeric", "aggregate": "numeric"},
    ),
    "S496_CD": TableDefinition(
        code="S496_CD",
        description="S-496 — candidate summary of financial activity",
        category="fact",
        tsv_files=["CalAccess/DATA/S496_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "amount": "numeric", "exp_date": "timestamp", "date_thru": "timestamp"},
    ),
    "S497_CD": TableDefinition(
        code="S497_CD",
        description="S-497 — candidate contributions detail",
        category="fact",
        tsv_files=["CalAccess/DATA/S497_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "elec_date": "timestamp", "ctrib_date": "timestamp", "date_thru": "timestamp", "amount": "numeric"},
    ),
    "S498_CD": TableDefinition(
        code="S498_CD",
        description="S-498 — candidate expenditures detail",
        category="fact",
        tsv_files=["CalAccess/DATA/S498_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "date_rcvd": "timestamp", "amt_rcvd": "numeric", "amt_attrib": "numeric"},
    ),
    "SMRY_CD": TableDefinition(
        code="SMRY_CD",
        description="Filing summaries (totals per filing)",
        category="fact",
        tsv_files=["CalAccess/DATA/SMRY_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "amount_a": "numeric", "amount_b": "numeric", "amount_c": "numeric", "elec_dt": "timestamp"},
    ),
    "SPLT_CD": TableDefinition(
        code="SPLT_CD",
        description="Split expenditure detail",
        category="fact",
        tsv_files=["CalAccess/DATA/SPLT_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "line_item", "pform_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer", "elec_date": "timestamp", "elec_amount": "numeric"},
    ),
    "TEXT_MEMO_CD": TableDefinition(
        code="TEXT_MEMO_CD",
        description="Free-text memos attached to records",
        category="fact",
        tsv_files=["CalAccess/DATA/TEXT_MEMO_CD.TSV"],
        conflict_columns=["amend_id", "filing_id", "form_type", "line_item", "rec_type"],
        type_coercions={"filing_id": "integer", "amend_id": "integer", "line_item": "integer"},
    ),
    # ------------------------------------------------------------------ #
    #  Non-TSV tables (populated via scrapers, not dbwebexport.zip)
    # ------------------------------------------------------------------ #
    "FILING_CALENDAR": TableDefinition(
        code="FILING_CALENDAR",
        description="Filing deadlines cross-referenced with election dates",
        category="dimension",
        tsv_files=[],
        conflict_columns=[],
        source="scrape",
    ),
    "ELECTION_RESULTS": TableDefinition(
        code="ELECTION_RESULTS",
        description="SOS election results PDF discovery metadata",
        category="dimension",
        tsv_files=[],
        conflict_columns=[],
        source="scrape",
    ),
}


def get_table_definitions() -> dict[str, TableDefinition]:
    """Return all registered table definitions."""
    return TABLE_DEFINITIONS


def get_facts() -> list[TableDefinition]:
    """Return only fact tables (financial records)."""
    return [
        v for v in TABLE_DEFINITIONS.values() if v.category == "fact"
    ]


def get_dimensions() -> list[TableDefinition]:
    """Return only dimension/reference tables."""
    return [
        v for v in TABLE_DEFINITIONS.values() if v.category == "dimension"
    ]


def get_all_codes() -> list[str]:
    """Return sorted list of all table codes."""
    return sorted(TABLE_DEFINITIONS.keys())
